sudo: required
services:
  - docker

before_install:
  - docker build -t thanhld97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thanhld97/react-test npm test -- --coverage

after_success:
  - docker build -t thanhld97/multi-client ./client
  - docker build -t thanhld97/multi-nginx ./nginx
  - docker build -t thanhld97/multi-server ./server
  - docker build -t thanhld97/multi-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push thanhld97/multi-client
  - docker push thanhld97/multi-nginx
  - docker push thanhld97/multi-server
  - docker push thanhld97/multi-worker
